version: '3'
services:
  composer:
    image: composer
    container_name: composer
    volumes:
      - .:/app
    user: ${DOCKER_HOST_USER_ID}:${DOCKER_HOST_USER_ID}
  apache-php:
    image: php:7.4-apache
    container_name: apache-php
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/schema.sql:/schema.sql


